In [2]:
# Day-6 (6-8-25)

# numpy - numerical computaion , ndimensional,vectorization,linera algebra, random numbers
# applicatin : ML ,image processing,computaion, finance

# pandas - data manupulation , data frames ,missing data , time series
# application : data cleaning , exploratory data analysis 

In [ ]:
# Indexing and Slicing 

print(arr3[1, 2])  # Second row, third column
What happens?:
-- Accesses the element at row index 1, column index 2 in arr3.
-- Output: 6 (from the 3x4 array shown earlier).

print(arr3[:, 1:3])  # All rows, columns 1-2
What happens?:
-- : this will selects all rows.
-- 1:3 selects columns at indices 1 and 2 (Python slices are upper bound exclusive).

In [4]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])          # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])   # 2D array

# Array operations (vectorization)
print(arr1 * 2)         # Multiply each element by 2
print(arr1 + arr1)      # Add arrays element-wise

# Reshaping
arr3 = np.arange(12).reshape(3, 4)        # Create 3x4 array from 0 to11
print(arr3)

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2))          # Matrix multiplication

# Statistical operations
data = np.random.normal(0, 1, 1000)       # 1000 random numbers from normal distribution
print(f"Mean: {data.mean()}, Std: {data.std()}")

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean: 0.03566325451120318, Std: 1.013734754973375


In [5]:
import pandas as pd
import numpy as np

# Creating DataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000


In [40]:
# to reading from CSV
# df = pd.read_csv('data.csv')

In [9]:
# Basic operations
print(df.head(2))             # First 2 rows

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000


In [10]:
print(df.describe())          # Summary statistics

             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000


In [11]:
print(df['Age'].mean())       # Average age

32.5


In [13]:
# Data selection
print(df[df['Age'] > 30])     # Filtering

      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000


In [14]:
print(df.loc[1:2, ['Name', 'Salary']])  # Selection by label

      Name  Salary
1      Bob   60000
2  Charlie   70000


In [17]:
# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]
})

print(df_with_nan.fillna(value=0))   # Replace NaN with 0

     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0


In [18]:
print(df_with_nan.dropna())         # Drop rows with NaN

     A    B
0  1.0  5.0
3  4.0  8.0


In [23]:
# Grouping and aggregation
df['Department'] = ['HR', 'Tech', 'Tech', 'HR']

In [29]:
print(df)

      Name  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000       Tech
2  Charlie   35   70000       Tech
3    David   40   80000         HR


In [34]:
print(df.groupby('Department')[['Age', 'Salary']].mean())

             Age   Salary
Department               
HR          32.5  65000.0
Tech        32.5  65000.0


In [35]:
# Merging DataFrames (like SQL joins)
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve'],
    'Bonus': [2000, 1500, 3000]
})
print(pd.merge(df, df2, on='Name', how='left'))  # Left join

      Name  Age  Salary Department   Bonus
0    Alice   25   50000         HR  2000.0
1      Bob   30   60000       Tech  1500.0
2  Charlie   35   70000       Tech     NaN
3    David   40   80000         HR     NaN


In [39]:
# Time series functionality
date_rng = pd.date_range(start='1/1/2023', end='1/10/2023', freq='D')
ts = pd.DataFrame(date_rng, columns=['date'])
ts['value'] = np.random.randint(0, 100, size=(len(date_rng)))
ts.set_index('date', inplace=True)
print(ts.resample('3D').mean())  # Resample to 3-day periods

                value
date                 
2023-01-01  37.000000
2023-01-04  67.333333
2023-01-07  45.333333
2023-01-10  66.000000
